config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'pages#index'
    resources :sweet_products, only: %i[index show]
    resources :categories, only: %i[index show]
  end

  get :search, to: 'pages#search'
  devise_for :admin_users, ActiveAdmin::Devise.config
  get '/admin/sweet_products/import', to: 'admin/sweet_products#import'
  post '/admin/sweet_products/import', to: 'admin/sweet_products#import_file'
  ActiveAdmin.routes(self)
  resource :call_me, only: [:create], controller: :call_me
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/call_me.rb
class CallMe < ApplicationRecord
  validates :phone, presence: { message: 'only numericality' },
                    numericality: true,
                    length: { minimum: 10, maximum: 15 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_sweet_products
  has_many :sweet_products, through: :category_sweet_products
end

app/models/category_sweet_product.rb
class CategorySweetProduct < ApplicationRecord
  belongs_to :category
  belongs_to :sweet_product
end

app/models/sweet_product.rb
class SweetProduct < ApplicationRecord
  has_one_attached :image
  has_many_attached :images

  has_many :category_sweet_products
  has_many :categories, through: :category_sweet_products

  has_rich_text :description

  validates :name, presence: true, length: { maximum: 20 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1 }

  # has_one :action_text_rich_text,
  #         class_name: 'ActionText::RichText',
  #         as: :record

  scope :sugar_substitute_true, -> { where(sugar_substitute: true) }
  scope :sugar_substitute_false, -> { where(sugar_substitute: false) }

  def category_names=(names)
    category_sweet_products.delete_all
    names.split(',').map(&:strip).uniq.each do |category_name|
      category_id = Category.find_or_create_by(name: category_name.to_s.downcase).id
      CategorySweetProduct.create(sweet_product_id: id, category_id: category_id)
    end
  end

  def category_names
    categories.map(&:name).join(' , ')
  end

  def set_image=(src)
    file = URI.parse(src).open
    image.attach(io: file, filename: name)
  rescue OpenURI::HTTPError => e
    pp e
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    sheet = spreadsheet.sheet(spreadsheet.sheets[0])
    header = sheet.row(sheet.first_row)
    (sheet.first_row + 1..sheet.last_row).each do |i|
      row = Hash[[header, sheet.row(i)].transpose]
      if row['id'].blank?
        sweet_product = SweetProduct.find_or_create_by(name: row['name'])
        row['id'] = sweet_product.id
      else
        sweet_product = SweetProduct.find_by(id: row['id'])
      end
      sweet_product.update(row)
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when '.csv' then Roo::Csv.new(file.path)
    when '.xls' then Roo::Excel.new(file.path)
    when '.xlsx' then Roo::Excelx.new(file.path)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  $PER_PAGE = 12

  private

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
    @locale = params[:locale] = I18n.locale
  end

  def default_url_options(options = {})
    {
      locale: I18n.locale
    }.merge options
  end

  def extract_locale
    params[:locale] || http_accept_language.compatible_language_from(I18n.available_locales).to_s
  end

  def sweet_products
    @sweet_products ||= SweetProduct.all
  end
  #
  # def find_in_text
  #   pp SweetProduct.includes(:action_text_rich_text).where("action_text_rich_text.body LIKE '%#{params[:search]&.downcase}%'")
  # end

  def search
    # find_in_text
    if (@search = params[:search])
      @sweet_products = sweet_products.where("lower(name) LIKE '%#{params[:search]&.downcase}%'")
    end
  end

  def pagination
    @count = sweet_products.count
    @sweet_products = sweet_products.page(page).per($PER_PAGE).with_attached_image.includes(:categories)
  end

  def page
    @page ||= (params[:page] || 1).to_i
  end
end

app/controllers/call_me_controller.rb
class CallMeController < ApplicationController
  def create
    call_me = CallMe.new(call_me_params)
    if call_me.save
      text = "Нова заявка на дзвінок \n
      #{call_me.phone}"
      Telegram::SendMessageJob.perform_later(text)
      # 1_000_000_000.times do |idea|
      #   pp idea
      # end
      redirect_back(fallback_location: root_path)
    else
      pp 'error'
    end
  end

  private

  def call_me_params
    params.require(:call_me).permit(:phone)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :categories
  def index; end

  def show
    @category = Category.find(params[:id])
    @sweet_products = @category.sweet_products
    search
    pagination
    respond_to do |format|
      format.js
      format.html
    end
  end

  def categories
    @categories ||= Category.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @sweet_products = SweetProduct.limit(8).with_attached_image.includes(:categories)
  end
end

app/controllers/sweet_products_controller.rb
class SweetProductsController < ApplicationController
  before_action :categories, only: %i[index search]

  def index
    search
    unless (@sugar_substitute = params[:sugar_substitute]).blank?
      @sweet_products = sweet_products.where(sugar_substitute: @sugar_substitute)
    end

    pagination
    respond_to do |format|
      format.js
      format.html
    end
  end

  def show
    @sweet_product = SweetProduct.find(params[:id])
  end

  private

  def categories
    @categories ||= Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_locale
    (I18n.locale || I18n.default_locale).to_s
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sweet_products_helper.rb
module SweetProductsHelper
  def sweet_product_image(image, width: 200, height: 200)
    image_tag (image.attached? ? image : '/nfd.jpg'), width: width, height: height, class: 'image'
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/sweet_products/import.html.erb
<%= form_tag admin_sweet_products_import_path, multipart: true, method: :post do %>
<%= file_field_tag :file %>
<%= submit_tag "import" %>
<% end %>

app/views/call_me/_form.html.erb
<%= form_for CallMe.new, url: call_me_path do |f| %>
  <%= f.text_field :phone %>
  <%= f.submit "Call mew"%>
<% end %>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category) %>

app/views/categories/index.html.erb
<h1>Перелік категорій</h1>
<%=render @categories%>

app/views/categories/show.html.erb
<div class="my-4">
  <h1 class="text-center" style="text-transform: uppercase"><%=@category.name%></h1>
  <%= render CatalogComponent.new(sweet_products: @sweet_products, categories: @categories)%>
</div>

app/views/categories/show.js.erb
catalog = document.getElementById("sweet_products")
catalog.innerHTML = '<%=j render(SweetProductComponent.with_collection(@sweet_products))%>'
pagination = document.getElementById("paginations")
pagination.innerHTML= '<%=j render "pages/paginations" %>'

app/views/layouts/_footer.html.erb
<footer class="py-4">
  <div class="container text-center">
    <%= link_to root_path, class:"navbar-brand" do %>
    "<%=t "navbar.title" %>"
    <%end%>
    <h3>Дякуємо що відвідали нас</h3>
    <small>Всі права захищено 2021</small>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light">
  <div class="container">
    <%= link_to t("navbar.catalog"), sweet_products_path%>

    <%= link_to root_path, class:"navbar-brand" do %>
    "<%=t "navbar.title" %>"
    <%end%>

    <%= form_tag url_for(), method: :get, class: "d-flex" do %>
      <%= text_field_tag(
          :search,
          params[:search],
          placeholder: t("navbar.search.placeholder"),
          class: "form-control  me-2"
      ) %>
            <button class="btn btn-marmelad" type="submit"><%=t "navbar.search.button" %></button>
    <% end %>
  </div>
</nav>
<header class="d-flex justify-content-start align-items-center">
  <div class="container">
    <h1 class="">Мармеладний Кіт це
      <div id="typed-strings">
        <p>марррммеладна насолода 🐈</p>
        <p>200 видів корисних цукерок</p>
        <p>альтернатива звичним солодощам</p>
        <p>скоро у твоєму місті (або обирай НП🚚)</p>
      </div>
      <span id="typed"></span>

    </h1>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Мармеладний кіт</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar"%>

      <div class="container">
        <%= yield %>
      </div>

      <%= render "layouts/footer"%>
  </body>
</html>

app/views/pages/_paginations.html.erb
<% if @count >$PER_PAGE%>
<ul class="pagination justify-content-center" >
  <%if @page > 1 %>
    <li class="page-item">
      <%= button_tag "previous", class:"page-link", data:{page: @page-1},onClick:"pagination_js(this);" %>
    </li>
    <%if @page > 2 %>
      <li class="page-item">
        <%= button_tag @page-2, class:"page-link", data:{page: @page-2},onClick:"pagination_js(this);" %>
      </li>
    <%end%>
    <li class="page-item">
      <%= button_tag  @page-1, class:"page-link", data:{page: @page-1},onClick:"pagination_js(this);" %>
    </li>
  <%end%>
  <li class="page-item disabled">
    <%= button_tag @page, class:"page-link" %>
  </li>
  <%if @page*$PER_PAGE<@count %>

    <li class="page-item">
      <%= button_tag @page+1,class:"page-link", data:{page: @page+1},onClick:"pagination_js(this);" %>
    </li>

    <%if (@page+1)*$PER_PAGE<@count %>
      <li class="page-item">
        <%= button_tag @page+2, class:"page-link", data:{page: @page+2},onClick:"pagination_js(this);" %>
      </li>
    <%end%>
    <li class="page-item">
      <%= button_tag t("next"), class:"page-link", data:{page: @page+1},onClick:"pagination_js(this);" %>
    </li>
  <%end%>
</ul>
<%end%>

app/views/pages/index.html.erb
<div class="row my-4">
  <div class="col-12">
    <h2 class="text-center">Рекомендовані товари</h2>
  </div>
  <%= render @sweet_products%>
</div>

app/views/sweet_products/_catalog.html.erb
<div class="catalog">

  <div class="row">
    <div class="col-12 col-md-2 col-lg-3">
      <% if @categories %>
        <ul>
          <% @categories.each do |category|%>
          <% if @category && category.id == @category.id %>
            <li><%=category.name%></li>
          <%else%>
            <li><%=render category%></li>
            <%end%>

          <%end%>
        </ul>
      <%end%>
      <%= select_tag :sugar_substitute, options_for_select([["Цукрозамінник",true],["Справжній цукор",false]]), onchange:"change_sugar_substitute(this)", prompt: "Тип цукру" %>
    </div>
    <div class="col-12 col-md-10 col-lg-9 row" id="sweet_products">

      <%= render @sweet_products%>

    </div>
  </div>
    <div id="paginations">
      <%= render "pages/paginations" %>
    </div>
</div>

app/views/sweet_products/_paginations.html.erb
<ul class="pagination justify-content-center" >
  <%if @page > 1 %>
    <li class="page-item">
      <%= button_tag "previous", class:"page-link", data:{page: @page-1},onClick:"pagination_js(this);" %>
    </li>
    <%if @page > 2 %>
      <li class="page-item">
        <%= button_tag @page-2, class:"page-link", data:{page: @page-2},onClick:"pagination_js(this);" %>
      </li>
    <%end%>
    <li class="page-item">
      <%= button_tag  @page-1, class:"page-link", data:{page: @page-1},onClick:"pagination_js(this);" %>
    </li>
  <%end%>
  <li class="page-item disabled">
    <%= button_tag @page, class:"page-link" %>
  </li>
  <%if @page*$PER_PAGE<@count %>

    <li class="page-item">
      <%= button_tag @page+1,class:"page-link", data:{page: @page+1},onClick:"pagination_js(this);" %>
    </li>

    <%if (@page+1)*$PER_PAGE<@count %>
      <li class="page-item">
        <%= button_tag @page+2, class:"page-link", data:{page: @page+2},onClick:"pagination_js(this);" %>
      </li>
    <%end%>
    <li class="page-item">
      <%= button_tag t("next"), class:"page-link", data:{page: @page+1},onClick:"pagination_js(this);" %>
    </li>
  <%end%>
</ul>

app/views/sweet_products/_sweet_product.html.erb
<div class="col-12 col-md-6 col-lg-3">
  <div class="card m-3">
    <%= link_to sweet_product_path(sweet_product) do %>
    <%= sweet_product_image(sweet_product.image) %>
    <div class="card-body row">
      <h5><%= sweet_product.name%></h5>
      <div class="tags text-left">
        <%sweet_product.categories.each do |category|%>
          <small><%= link_to category.name, category_path(category),class: "badge bg-secondary"%></small>
        <%end%>
      </div>
    </div>
  <%end%>
</div>
</div>

app/views/sweet_products/index.html.erb
<div class="my-4">
  <h1 class="text-center">Каталог</h1>
  <%= render CatalogComponent.new(sweet_products: @sweet_products, categories: @categories)%>
</div>

app/views/sweet_products/index.js.erb
catalog = document.getElementById("sweet_products")
catalog.innerHTML = '<%=j render(SweetProductComponent.with_collection(@sweet_products))%>'
pagination = document.getElementById("paginations")
pagination.innerHTML= '<%=j render "pages/paginations" %>'

app/views/sweet_products/search.html.erb
<h1>Результати пошуку за "<%= @search %>"
</h1>
<h5>Кількість результатів
  <%= @sweet_products.count %></h5>
  <div class="row" id="sweet_products">

    <%= render @sweet_products%>

  </div>
  <% if @count > $PER_PAGE%>
    <%= render "paginations" %>
  <%end%>

app/views/sweet_products/set_page.js.erb
// console.log("js work!")
catalog = document.getElementById("sweet_products")
catalog.innerHTML = '<%=j render @sweet_products%>'
pagination = document.getElementById("paginations")
pagination.innerHTML= '<%=j render "paginations" %>'

app/views/sweet_products/show.html.erb
<div class="my-4">
  <div class="row">
    <div class="col-12 col-md-6 col-xl-5">
      <% @sweet_product.images.each do|image|%>
        <%= image_tag image, width: "100%"%>
      <%end%>
      <%= sweet_product_image @sweet_product.image, height: "100%", width: "100%"%>
    </div>
    <div class="col-12 col-md-6 col-xl-7">
      <h1 class="pb-0 mb-0">
        <%= @sweet_product.name%>
      </h1>
      <div class="tags mb-3">
        <%@sweet_product.categories.each do |category|%>
          <%= link_to category.name, category_path(category),class: "badge bg-secondary"%>
        <%end%>
      </div>
      <span class="d-block my-3">
        <b><%= @sweet_product.price%> грн. </b>
        за 100 грам
      </span>

      <div class="my-3">
        <%= render "call_me/form"%>
      </div>


        <h5 class="mb-0 pb-0">Опис:</h5>
        <div class="mt-1">
          <%= @sweet_product.description%>
        </div>

    </div>
  </div>
</div>